

# Project information
site_name: Mohsin | Projects Docs
site_description: Mohsin Mahmood Projects Documentations
site_author: Mohsin Mahmood
site_url: https://mohsinmdl.github.io


# Copyright
copyright: 'Copyright &copy; 2016 - 2019 Martin Donath'

nav:
  - Django | Heroku: index.md
  - Git Guide 101:  git-guide-101.md
  - Flask Guide 101: flask-doc\Flask Guide 101.md
  - Design Pattern:
    - What is Design Pattern: designPattern\design-pattern-intro.md
    - Creational Pattern: designPattern\creational\creational-dp.md
    - Structural Pattern: designPattern\structural\structural-dp.md
    - Behaviour Pattern: designPattern\behavioural\behaviour-dp.md
  - Contact:
    - About: Contact/about.md
    - Markdown: output.md
  - Assignment: Contact/ass2.md

theme:
  name : 'material'
  palette:
    primary: 'Teal'
    accent: 'Teal'

# Extensions
markdown_extensions:
  - markdown_include.include:
          base_path: docs
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      linenums: true #Adding Line Number to the Code
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde



# Customization
extra:
  social:
    - type: globe
      link: http://mohsinmahmood.me
    - type: github-alt
      link: https://github.com/mohsinmdl
    - type: twitter
      link: https://twitter.com/joinmohsinmdl
    - type: linkedin
      link: https://linkedin.com/in/mohsinmdl